### ISSUE TITLE
Commit composer.lock

### ISSUE THREAD

**Issue by graseggergh** [directus/v8-archive#1845]
# Feature Request

## What problem does this feature solve?

Installing the dependencies breaks the project.

## How do you think this should be implemented?

Commit the composer.lock

## Would you be willing to work on this?

Yes.

**Comment by benhaynes** [comment]
We've discussed this a lot... @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
It was there, then there was an issue / PR stating, we should remove it, and now we've come full circle with an issue saying we should add it back 🤷‍♂ 

I'm a little confused by 

> Installing the dependencies breaks the project.

though, we install the composer dependencies fresh on every release too, and that has never been an issue

**Comment by graseggergh** [comment]
Hi, I can't reproduce this anymore, so I  am going to close it.
