### ISSUE TITLE
auth.login returns 404 

### ISSUE THREAD

**Issue by ratsey** [directus/v8-archive#2396]
Installed version: 8.8.1 via Softaculous install
MariaDB

I can successfully authenticate a user from Insomnia REST client using:

`POST: https://apitest.mydomain.com/myapp/auth/authenticate`
with an {email,password,mode} payload

When passing the same payload via the SDK I get a 404, but note that the endpoint is different:

`this.directus.auth.login({email: this.#email, password: this.#password})`

Issues a call to:

`https://apitest.mydomain.com/myapp/auth/login`
{"error":{"code":1,"message":"Not Found"}}

Is this a configuration issue or perhaps a mismatch in versions?

**Comment by rijkvanzanten** [comment]
Looks like you're using Directus v8, but the SDK for v9 🙂

**Comment by rijkvanzanten** [comment]
The SDK now follows the Directus version, so SDK-v9.0.0-rc.35 matches Directus v9.0.0-rc.35 etc. Therefore, any SDK version < 9x can be used with v8

**Comment by ratsey** [comment]
Thanks, I figured perhaps a mismatch. I've not been able to install v9 on my shared host (errors on install that CXXABI_1.3.8 is missing) so trying to make do with 8.8.1 from their Softaculous offering.

How can I reference a v8 SDK? 

`npm view directus versions`

shows only 'preview' and version 9 builds.

**Comment by ratsey** [comment]
Ignore. 

[npm view "@directus/sdk-js" versions](url)

;-)

**Comment by ratsey** [comment]
Sorry for bouncing the issue status.

Don't see any explicit v8 SDK version. Tried 6.3.0 as 'latest' non-9 version, but can't even get a client instanced using the v8 docs:

https://v8.docs.directus.io/guides/js-sdk.html#installation

**Comment by rijkvanzanten** [comment]
This might help you get started:

https://github.com/directus/v8-archive/blob/master/sdk/sdk-js/recipes/Starter.md

**Comment by ratsey** [comment]
That didn't seem to work for me either.

I poked around the repo and came up with this, which does work:

```
sdk = new SDK({url: "MyURL", project: "MyProject", mode: "cookie"});
...
this.sdk.login( {email: "MyEmail", password: "MyPassword"});
```

I see that it returns a cookie, as expected but any subsequent calls are giving a 401 Unauthorized. Isn't cookie mode supposed to handle that for me?

Again, apologies for not being able to use v9 which seems like a huge improvement.

**Comment by ratsey** [comment]
For anyone who comes across this issue. The problem is related to CORS. Running on localhost, Chrome will accept the authentication cookie but not write it, so any following request will show as unauthorised. Switch the environment CORS settings to allow and all is good. Just remember to set back after local testing is done.
